server:
  port: 8100

spring:
  application:
    name: auto

  datasource:
    url: jdbc:mysql://localhost:3306/auto
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: mysql

